version: "3.8"
services:
  db:
    image: postgres:15
    container_name: hotels_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotelsdb
    ports:
      - 5433:5432 # Порт нужен, только если нам нужен доступ к контейнеру напрямую

  redis:
    image: redis:7
    container_name: hotels_redis

  hotels:
    build:
      context: .
    container_name: hotels_app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: ["/app/docker/app.sh"]
    ports:
      - 8080:8000

  celery:
    build:
      context: .
    container_name: hotels_celery
    command: ["/app/docker/celery.sh", "celery"] # Второй аргумен для if/elif в скрипте
    env_file:
      - .env
    depends_on:
      - redis

  flower:
    build:
      context: .
    container_name: hotels_flower
    command: ["/app/docker/celery.sh", "flower"]
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - 5555:5555

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    volumes:
      - grafanadata:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000

volumes:
  postgresdata:
  grafanadata:
  prometheusdata: